---
dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.4
  icons_launcher: ^2.1.7


  intl: ^0.19.0
  loading_indicator: ^3.1.1
  
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
icons_launcher:
  image_path: "images/zz.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      generate: true
      image_path: "images/zz.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "images/zz.png"
      icon_size: 48 
environment:
  sdk: '>=3.4.0-104.0.dev <4.0.0'
flutter:
  uses-material-design: true
name: ai_x1
publish_to: none
version: 1.0.0+1